# Site settings
title: leg
email: mail@leg.ninja
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
include: ['_pages']
sass:
    sass_dir: _sass

# Navigation
nav:
  IRC: /irc
  Contactos: /contactos

# Page defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"